#!/bin/bash

# CCache
CCACHEDIR=~/.ccache/minimal;
mkdir -p $CCACHEDIR;
export USE_CCACHE=1;
export CCACHE_NLEVELS=4;
export CCACHE_DIR=$CCACHEDIR;

# Ask whether to do a repo sync before building
echo -e "Perform repo sync before building? [Y for 'Yes']"; 
read rep;
    echo "";
    case $rep in
        y|Y )
            repo sync -j8
            ;;
        * )
            ;;
    esac

# Build
. build/envsetup.sh;
export KBUILD_BUILD_USER=darkfalcon;
export KBUILD_BUILD_HOST=ArchBox;
#export ENABLE_GCCONLY=true;
#export SUPPRES_UNUSED_WARNING=true;
#export GRAPHITE_OPTS=true;
#export KRAIT_TUNINGS=true;
#export FFAST_MATH=true;
#export FLOOP_NEST_OPTIMIZE=true;

lunch minimal_osprey-userdebug;
export USE_PREBUILT_CHROMIUM=true;
export CHANGELOG=true;

# Ask whether to make a clean build or a dirty one
echo -e "Perform a clean build? [Y/N]"; 
read mka;
    echo "";
    case $mka in
        y|Y )
            mka clean && mka bacon;
            ;;
        n|N )
            mka bacon;
            ;;
        * )
            echo "Please answer in Yes or No." && exit
            ;;
    esac
