#!bin/bash

#Makes life easier
MINIMAL="/home/darkfalcon/minimal";
LMANIFESTS="$PWD/.repo/local_manifests";

#Quick check if the source directory exists
if [ ! -d "$MINIMAL" ]; then
  echo "No valid working directory found. Exiting...";
  exit;
else
  echo "Found woking directory!";
fi

#Copy files to respective directories 
cp "compile" "$MINIMAL";
cp "reset" "$MINIMAL";

echo -e "Copy local manifests? (includes roomservice.xml) [Y/N]"; 
read cop;
    echo "";
    case $cop in
        y|Y )
            cd $LMANIFESTS;
            rm "$MINIMAL/.repo/local_manifests/local_manifest.xml";
            cp "local_manifest.xml" "$MINIMAL/.repo/local_manifests/";
            ;;
        n|N )
            echo "Local manifests not copied." && break
            ;;
        * )
            echo "Please answer in Yes or No." && exit
            ;;
    esac

echo "Done!";

exit
