#!bin/bash

#Makes life easier

MINIMAL="/home/darkfalcon/minimal";
LMANIFESTS="$PWD/.repo/local_manifests";
VPRODUCT="$PWD/vendor/minimal/products";

#Quick check if the source directory exists

if [ ! -d "$MINIMAL" ]; then
  echo "No valid working directory found. Exiting...";
  exit;
else
  echo "Found woking directory!";
fi

#Copy files to respective directories 

cp "clean" "$MINIMAL";
cp "compile" "$MINIMAL";
cp "reset" "$MINIMAL";

cd $LMANIFESTS;
rm "$MINIMAL/.repo/local_manifests/local_manifest.xml" && cp "local_manifest.xml" "$MINIMAL/.repo/local_manifests/";
echo "'local_manifest.xml' copied to path '/.repo/local_manifests/'";

cd $VPRODUCT;
rm "$MINIMAL/vendor/minimal/products/AndroidProducts.mk" && cp "AndroidProducts.mk" "$MINIMAL/vendor/minimal/products/";
cp "minimal_pepper.mk" "$MINIMAL/vendor/minimal/products/";
echo "'AndroidProducts.mk' & 'minimal_pepper.mk' copied to path '/vendor/minimal/products/'";

echo "Done!";

exit
